const pt = (value: string) => ({ "pt-BR": value });

export const C1_LESSONS = [
  {
    key: "lesson.swd.c1.how_hand_moves",
    version: 1,
    unitKey: "unit.swd.c1.movement",
    title: pt("Como sua mão se move"),
    objective: pt("Perceber quando pulso, cotovelo e ombro ajudam em escalas diferentes de movimento."),
    estimatedActiveMinutes: 6,
    blocks: [
      { type: "HOOK" as const, text: pt("Controle começa antes do traço: começa escolhendo como o corpo vai executar o movimento.") },
      { type: "TEXT" as const, title: pt("Três escalas de movimento"), text: pt("Pulso favorece movimentos pequenos; cotovelo amplia o arco; ombro ajuda em traços longos e fluidos. O objetivo é ganhar opções, não seguir uma regra rígida.") },
      { type: "DEMONSTRATION" as const, title: pt("Teste o mesmo traço"), steps: [pt("Faça curto com o pulso"), pt("Repita usando mais o cotovelo"), pt("Faça uma versão longa usando o ombro"), pt("Compare estabilidade e conforto")] },
    ],
  },
  {
    key: "lesson.swd.c1.point_to_point",
    version: 1,
    unitKey: "unit.swd.c1.straight_lines",
    title: pt("Point to Point"),
    objective: pt("Planejar origem, destino e direção antes de executar uma linha reta."),
    estimatedActiveMinutes: 8,
    blocks: [
      { type: "HOOK" as const, text: pt("Uma linha boa não começa quando o lápis toca o papel. Ela começa quando você decide origem e destino.") },
      { type: "DEMONSTRATION" as const, title: pt("Look · Plan · Ghost · Commit"), steps: [pt("Olhe os dois pontos"), pt("Planeje a direção"), pt("Simule o gesto no ar"), pt("Execute sem corrigir o caminho aos poucos")] },
      { type: "PRACTICE" as const, exerciseKey: "exercise.swd.gym.intentional_line", title: pt("Treine agora"), text: pt("Faça algumas tentativas de linha intencional e observe o feedback do Coach.") },
    ],
  },
  {
    key: "lesson.swd.c1.curve_control",
    version: 1,
    unitKey: "unit.swd.c1.curves",
    title: pt("Curvas C e S"),
    objective: pt("Construir curvas contínuas com ritmo em vez de pequenos segmentos corrigidos."),
    estimatedActiveMinutes: 8,
    blocks: [
      { type: "TEXT" as const, title: pt("Curva também é decisão"), text: pt("Curvas C e S aparecem em gesture, anatomia, design e contornos. Treine o movimento como uma trajetória inteira.") },
      { type: "DEMONSTRATION" as const, title: pt("Famílias de curva"), steps: [pt("C aberta"), pt("C fechada"), pt("S suave"), pt("S mais comprimida"), pt("Repita mudando escala e orientação")] },
      { type: "PRACTICE" as const, exerciseKey: "exercise.swd.gym.curve_path", title: pt("Curve Path"), text: pt("Percorra uma trajetória curva contínua mantendo estabilidade.") },
    ],
  },
  {
    key: "lesson.swd.c1.circle_ellipse",
    version: 1,
    unitKey: "unit.swd.c1.circles_ellipses",
    title: pt("Círculos e elipses"),
    objective: pt("Executar movimentos circulares contínuos e começar a perceber eixo e orientação da elipse."),
    estimatedActiveMinutes: 9,
    blocks: [
      { type: "HOOK" as const, text: pt("Círculos e elipses não são desenhados aos pedaços: são movimentos completos.") },
      { type: "TEXT" as const, title: pt("Ghost antes de executar"), text: pt("Simule a trajetória circular uma ou duas vezes e execute de forma contínua. Na elipse, observe também a direção do eixo.") },
      { type: "PRACTICE" as const, exerciseKey: "exercise.swd.gym.ellipse_control", title: pt("Ellipse Control"), text: pt("Treine elipses dentro de limites para desenvolver consistência.") },
    ],
  },
  {
    key: "lesson.swd.c1.direction_parallelism",
    version: 1,
    unitKey: "unit.swd.c1.direction_parallelism",
    title: pt("Direção e paralelismo"),
    objective: pt("Repetir uma direção com consistência e controlar relações entre linhas."),
    estimatedActiveMinutes: 8,
    blocks: [
      { type: "TEXT" as const, title: pt("Uma linha conversa com a outra"), text: pt("Linhas paralelas, convergentes e orientadas preparam construção, perspectiva e hatching. Compare direção antes de comparar detalhe.") },
      { type: "DEMONSTRATION" as const, title: pt("Rails"), steps: [pt("Desenhe uma linha guia"), pt("Planeje a segunda direção"), pt("Mantenha distância aproximada"), pt("Compare início, meio e fim")] },
      { type: "PRACTICE" as const, exerciseKey: "exercise.swd.gym.parallel_rails", title: pt("Parallel Rails"), text: pt("Treine manter duas linhas relacionadas sem microcorreções.") },
    ],
  },
  {
    key: "lesson.swd.c1.pressure_line_weight",
    version: 1,
    unitKey: "unit.swd.c1.pressure",
    title: pt("Pressão e line weight"),
    objective: pt("Variar intensidade do traço de forma deliberada."),
    estimatedActiveMinutes: 7,
    blocks: [
      { type: "TEXT" as const, title: pt("Leve, médio, forte"), text: pt("Pressão é mais uma decisão disponível. Ela pode organizar leitura, indicar ênfase e preparar rendering, mas primeiro precisamos conseguir variá-la de propósito.") },
      { type: "DEMONSTRATION" as const, title: pt("Taper"), steps: [pt("Leve → forte"), pt("Forte → leve"), pt("Mantenha a direção"), pt("Repita sem aumentar tensão na mão")] },
      { type: "CHECKPOINT" as const, text: pt("Em dispositivos sem sensibilidade à pressão, faça este treino no papel ou com brushes de tamanho controlado.") },
    ],
  },
  {
    key: "lesson.swd.c1.rhythm_confidence",
    version: 1,
    unitKey: "unit.swd.c1.rhythm_confidence",
    title: pt("Ritmo e confiança"),
    objective: pt("Encontrar uma faixa de velocidade que preserve intenção e fluidez."),
    estimatedActiveMinutes: 8,
    blocks: [
      { type: "HOOK" as const, text: pt("Mais lento nem sempre significa mais preciso.") },
      { type: "TEXT" as const, text: pt("Traços excessivamente lentos podem acumular pequenas correções. Compare versões lentas, controladas e rápidas para encontrar uma faixa estável.") },
      { type: "REFLECTION" as const, prompt: pt("Qual sensação você busca no traço?"), options: [pt("Movimento decidido e controlado"), pt("Velocidade máxima"), pt("Correção constante durante o caminho")] },
    ],
  },
  {
    key: "lesson.swd.c1.applied_line",
    version: 1,
    unitKey: "unit.swd.c1.applied_line",
    title: pt("Linha aplicada"),
    objective: pt("Transferir controle abstrato para um objeto simples observado."),
    estimatedActiveMinutes: 10,
    blocks: [
      { type: "HOOK" as const, text: pt("Drill só vale quando a habilidade aparece no desenho real.") },
      { type: "TEXT" as const, title: pt("Line economy"), text: pt("Observe um objeto simples e tente descrevê-lo com menos traços, mas mais deliberados. Menos linhas não é uma regra estética: é um exercício de decisão.") },
      { type: "DEMONSTRATION" as const, title: pt("Aplicação"), steps: [pt("Observe o contorno geral"), pt("Escolha trechos principais"), pt("Planeje cada direção"), pt("Execute sem serrilhar"), pt("Compare o conjunto antes de detalhar")] },
      { type: "CHECKPOINT" as const, text: pt("Ao concluir C1, o objetivo não é ter linha perfeita. É demonstrar controle funcional e um processo repetível.") },
    ],
  },
] as const;
